### PR TITLE
Remove copy of Niworkflows in favor of dependency

### PR DESCRIPTION
**Pull request by tsalo**
## Changes proposed in this pull request

- Remove copy of niworkflows.
- Add niworkflows as a requirement.
- Bump svgutils requirement from 0.3.0 to 0.3.4 (for niworkflows compliance).
- Add copies of interfaces from the qsiprep copy of niworkflows to the interfaces.niworkflows module, for niworkflows interfaces that have been removed (or renamed in such a way that I couldn't track down the new version) from niworkflows in the versions since a copy was made in qsiprep.
    - RobustMNINormalizationRPT
- Move plot_denoise, plot_acpc, and slices_from_bbox functions to viz.utils module.

### CODE REVIEW

**Comment by mattcieslak** [comment]
I'm so happy to see that this works. In an unrelated PR, do you know if this change means we can remove the CRN_SHARED_DATA and `/niworkflows` directory from the docker build?

**Comment by tsalo** [comment]
I don't know about `CRN_SHARED_DATA`, but it does seem like `/niworkflows` could be removed.

**Comment by tsalo** [comment]
@mattcieslak it looks like you made changes to something in the local niworkflows copy. Do you want me to address the conflict, or would you be willing to (just because you would know better what you changed)?

**Comment by mattcieslak** [comment]
it's bizarre, I can't click the "resolve conflicts" button because it says the conflicts are too complex to resolve in a web browser. That's a new one

**Comment by tsalo** [comment]
I think it's because my branch removes the file completely, while you actually changed the contents in `master`.

**Pull request merged**
