### PR TITLE
[ENH] Update pyafq; add pyafq full test

### PR DESCRIPTION
**Pull request by 36000**
This PR updates pyAFQ to 1.0.1 and adds a test for the "full" run of pyafq (use dipy tractography instead of mrtrix). Also updates names/docs of pyAFQ to be more clear.

### CODE REVIEW

**Comment by mattcieslak** [comment]
@36000 let me know when you'd like a review and I'll merge this

**Comment by 36000** [comment]
@mattcieslak ready for review / merge!

**Comment by 36000** [comment]
@mattcieslak actually, hold up on merging this. I want to see if it resolves one of the posted issues first.

**Comment by richford** [comment]
@mckenziephagen and I are anxiously awaiting this merge! We'll use it to kick off the ABCD pyAFQ runs. Thanks so much @mattcieslak and @36000!

**Review by mattcieslak — APPROVED** [review]

**Comment by richford** [comment]
Wow! That was fast. @mattcieslak, any chance you could cut a release or RC with this?

**Comment by mattcieslak** [comment]
0.17.0 should be up in a bit. @36000 are there any shortcuts to make the CI test run faster? It looks like it's taking 90 minutes to run as it's currently implemented

**Comment by 36000** [comment]
I think the easiest thing to do would be to reduce the number of seeds for tractography and/or comment out one of the two portions of the test. I will make a PR that does this tomorrow.

**Pull request merged**
