### PR TITLE
Update pyAFQ version to 1.1

### PR DESCRIPTION
**Pull request by arokem**
Would this build a new qsiprep container with the new pyAFQ version? Would a user then have to use `latest` to access this version of pyAFQ, until a new RC of qsiprep is up?

### CODE REVIEW

**Comment by arokem** [comment]
Oh - this is going to be an issue for this upgrade: 

https://app.circleci.com/pipelines/github/PennLINC/qsiprep/1523/workflows/f315e32e-057a-49e9-89f7-b3a2b521701e/jobs/15292

```
ERROR: Cannot install qsiprep and qsiprep==0.19.0+4.gfc32817 because these package versions have conflicting dependencies.

The conflict is caused by:
    qsiprep 0.19.0+4.gfc32817 depends on pybids<0.16.1
    pyafq 1.1 depends on pybids>=0.16.2

```

How strict is the need for the earlier pybids here?

**Comment by mattcieslak** [comment]
not strict at all, we can bump pybids. Once this passes I'll do a RC!

**Comment by mattcieslak** [comment]
Turns out that the new pybids needs a different regex to filter out dotfiles. Credit goes to @tsalo for this discovery

**Comment by mattcieslak** [comment]
We ended up adding an even newer pyafq in #729

**Pull request closed without merging**
