### PR TITLE
DOC: Improve installation instructions

### PR DESCRIPTION
**Pull request by jhlegarreta**
Improve installation instructions:
- Explicitly mention the possibility of installing `qsiprep` through PyPI, and the required additional dependencies.
- Clarify how this is different from using containers and the `qsiprep-container` PyPI package.

### CODE REVIEW

**Comment by tsalo** [comment]
I believe we removed the PyPi deployment. @mattcieslak is that correct?

**Comment by tsalo** [comment]
Okay cool. @jhlegarreta I can take over this PR since it's been so long since you opened it (sorry about that), unless you have the time to work on it now?

**Comment by jhlegarreta** [comment]
@tsalo I see that you have already opened a PR and I see that the text is different from what I proposed, discouraging the use of `PyPI`, so I guess you have a better understanding of who the tool should be installed. Thanks.

**Comment by tsalo** [comment]
Sorry, I got a little over-eager. I think with any of the preps, installing with PyPi is strongly discouraged except for power users (who are probably forking the repo and cloning it locally TBH).

**Pull request closed without merging**
