### PR TITLE
Remove underscore versions of all parameters

### PR DESCRIPTION
**Pull request by tsalo**
Closes none. This is a breaking change because parameter names have effectively been changed.

## Changes proposed in this pull request

- Remove underscore versions of all parameters (e.g., `--anat_only` instead of `--anat-only`).
- Add dash versions where they were missing.

### CODE REVIEW

**Review by mattcieslak — APPROVED** [review]
didn't fmriprep get rid of the underscore versions? I'm ok with keeping them here

**Comment by tsalo** [comment]
Oh you're right! I might have corrected in the wrong direction. Do you have any issue with me reversing this and dropping the underscore versions?

**Comment by mattcieslak** [comment]
I trust the fmriprep folks on this decision

**Comment by tsalo** [comment]
Okay cool, I'll reverse my changes.

**Review by mattcieslak — APPROVED** [review]

**Pull request merged**
