### PR TITLE
[ENH] Add pyafq

### PR DESCRIPTION
**Pull request by 36000**
This PR adds PyAFQ as a Reconstruction workflow.

### CODE REVIEW

**Comment by 36000** [comment]
I still have some TODO's left. However,  I am currently running into this bug after pyAFQ finishes running: 
`traits.trait_errors.TraitError: Each element of the 'in_file' trait of a DerivativesDataSinkInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/scratch/qsirecon_wf/sub-ABCD_pyAFQ_full/sub_ABCD_acq_10per000_space_T1w_desc_preproc_recon_wf/pyAFQ_full/run_afq/study/subject/PYAFQ' <class 'str'> was specified.`

**Comment by mattcieslak** [comment]
I wonder if the datasink can't handle a directory.

**Comment by mattcieslak** [comment]
Is the biascorrection node running in your local tests? Strange to see it crashing on circleci

**Comment by 36000** [comment]
It is failing locally as well. Is it caused by the "update for mrtrix3 update" commit? Not sure how that got into the PR

https://github.com/PennLINC/qsiprep/pull/398/commits/785f1ee307b2d5cff3a125a18a94ea7fe33597de

**Comment by 36000** [comment]
This is mostly done, just running into this error at the end:
```
ERROR:nipype.workflow:Node ds_pyAFQ_full failed to run on host 9fa8d2d83851.
220420-21:15:10,45 nipype.workflow ERROR:
	 Saving crash info to /out/qsirecon/sub-ABCD/log/20220420-204605_093d1b65-004d-4e1e-9bd4-270f79c5996e/crash-20220420-211510-UID501-ds_pyAFQ_full-b74059e7-a869-44fa-a50b-37886a7de309.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node ds_pyAFQ_full.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/bids.py", line 386, in _run_interface
    self._results['compression'].append(_copy_any(fname, out_file))
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/bids.py", line 561, in _copy_any
    copyfile(src, dst, copy=True, use_hardlink=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/utils/filemanip.py", line 435, in copyfile
    shutil.copyfile(originalfile, newfile)
  File "/usr/local/miniconda/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/'
```

**Comment by mattcieslak** [comment]
This is awesome. I'm going to start testing this locally and get circleci to test it directly

**Comment by 36000** [comment]
@mattcieslak  any progress on this ? I can try to dig into what is causing this error as well, but I am not sure where to start. Is it the output node from pyAFQ that is causing this? All of pyAFQ runs before this error.

**Comment by mattcieslak** [comment]
This is running locally for me now, but I'm seeing a new error on circleci https://app.circleci.com/pipelines/github/PennLINC/qsiprep/1094/workflows/78eb36de-675b-41ba-b0f7-48e61f0cca11/jobs/8719

**Comment by 36000** [comment]
I think this is a pyAFQ bug where we are using op.split('.') instead of op.splitext() , so other '.' in paths cause problems. I will fix this in pyAFQ and make a minor release.

**Comment by mattcieslak** [comment]
sounds good, let me know when it's up. I added a minor fix to the docs build. Also, should we add some text to the documentation in this PR or a separate one?

**Comment by 36000** [comment]
We will make a minor release today likely, to double check that it fixes the above bug. We will update pyAFQ to 1.0 soon (I think this week), so we can wait for that to merge this. 
For the documentation, I can add text to this PR in the meantime. Is there a good example from another pipeline that I should work off of?

**Comment by mattcieslak** [comment]
Excellent!! Here is where the documentation for reconstruction workflows goes: https://github.com/PennLINC/qsiprep/blob/master/docs/reconstruction.rst#dsi_studio_gqi.

**Comment by 36000** [comment]
@mattcieslak Once these tests finish this is ready to go. For each important pyAFQ update I can open a PR to keep QSIPrep up to date, and that should be a very quick process (just update version number and updated JSON files if parameters changed, where the JSON files are auto-generated by pyAFQ)

**Comment by mattcieslak** [comment]
This looks awesome!

**Pull request merged**
